apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-list-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: flask-list-app
    spec:
      containers:
      - name: flask-pod
        image: ghcr.io/m-1990/flask-toronto:v3
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 130Mi
            cpu: 0.1
      imagePullSecrets:
      - name: ghcr-secret
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - flask-list-app
            topologyKey: kubernetes.io/hostname
