name: 'CI/CD for Flask App'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_ID: 'gke-handson-459103'
  GKE_CLUSTER: 'gke-cluster'
  GKE_ZONE: 'us-central1-c'
  DEPLOYMENT_NAME: 'deploy.yaml'
  SVC_NAME: 'svc.yaml'
  NAMESPACE: 'app'
  IMAGE: 'flask-toronto'

jobs:
  build:
    name: build image and push
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/flask-toronto:latest
      - name: echo variables
        run: |
          echo "cluster name: ${{ env.GKE_CLUSTER }}"
      - name: Authenticate with GKE Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - name: Get the GKE credentials to deploy to the cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: deploy to cluster
        run: |-
         kubectl apply -f ${{ env.DEPLOYMENT_NAME }} -n ${{env.NAMESPACE}}
         kubectl apply -f ${{ env.SVC_NAME }} -n ${{env.NAMESPACE}}
         kubectl get pods -n ${{env.NAMESPACE}}
